# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-06 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0003_auto_20191006_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='editor',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
